App\Entity\Location:
    properties:
        latitude:
            - Range:
                  min: -90
                  max: 90
                  groups: ['create', 'edit']
                  notInRangeMessage: "Latitude must be between {{ min }} and {{ max }}."
        longitude:
            - Range:
                  min: -180
                  max: 180
                  groups: ['create', 'edit']
                  notInRangeMessage: "Longitude must be between {{ min }} and {{ max }}."

App\Entity\Measurement:
    properties:
        celsius:
            - Range:
                  min: -100
                  max: 100
                  groups: ['create', 'edit']
                  notInRangeMessage: "Temperature must be between {{ min }} and {{ max }}."
        humidity:
            - Range:
                  min: 0
                  max: 100
                  groups: ['create', 'edit']
                  notInRangeMessage: "Humidity must be between {{ min }} and {{ max }}."
